# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Cherry Pick commits from PR

trigger:
- fasttrack/*
- tvuong/fasttrack/*
pr: none

variables:
  - name: pipelinesRepoFolder
    value: 'CBL-Mariner-Pipelines'

  - name: pipelinesRepoRoot
    value: $(Agent.BuildDirectory)/$(pipelinesRepoFolder)

resources:
  repositories:
    - repository: CBL-Mariner-Pipelines
      type: git
      name: mariner/CBL-Mariner-Pipelines
      ref: refs/heads/tvuong/cherry-pick

jobs:
  steps:
  - checkout: CBL-Mariner-Pipelines
    path: $(pipelinesRepoFolder)

  - template: spec-auto-patch-update/pipelines/CherryPick.yml@CBL-Mariner-Pipelines
    parameters:
      commitId: $(Build.SourceVersion)
      sourceBranch: $(Build.SourceBranchName)
      repoRootPath: $(pipelinesRepoRoot)
