# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Cherry Pick commits from PR

trigger:
- fasttrack/*
- tvuong/fasttrack/*
pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: mariner/CBL-Mariner-Pipelines
      ref: refs/heads/tvuong/cherry-pick

jobs:
  - template: spec-auto-patch-update/pipelines/CherryPick.yml@templates
    parameters:
      commitId: $(Build.SourceVersion)
      sourceBranch: $(Build.SourceBranchName)
