# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Cherry Pick commits from PR

trigger:
- fasttrack/*
- tvuong/fasttrack/*
pr: none

variables:
  - name: pipelinesRepoFolder
    value: 'CBL-Mariner-Pipelines'

  - name: pipelinesRepoRoot
    value: $(Agent.BuildDirectory)/$(pipelinesRepoFolder)

resources:
  repositories:
    - repository: CBL-Mariner-Pipelines
      type: git
      name: mariner/CBL-Mariner-Pipelines
      ref: refs/heads/tvuong/cherry-pick

jobs:
  - job: 'CherryPick'
    pool: mariner-core-x64-1es-ubuntu-22.04
    timeoutInMinutes: 15
    displayName: 'Cherry-pick commit'

    steps:
    - checkout: CBL-Mariner-Pipelines
      path: $(pipelinesRepoFolder)
      displayName: 'Checkout CBL-Mariner'

    - template: spec-auto-patch-update/pipelines/CherryPick.yml@CBL-Mariner-Pipelines
      parameters:
        commitId: $(Build.SourceVersion)
        sourceBranch: $(Build.SourceBranchName)
        repoRootPath: $(pipelinesRepoRoot)
