iso:
  kernelCommandLine:
    extraCommandLine: "url=http://1.2.3.4"
  additionalFiles:
    initrd-additional-artifacts/esp.raw.zst: /esp.raw.zst
    initrd-additional-artifacts/root.raw.zst: /root.raw.zst
os:
  users:
  - name: test
    password: testpassword
    primaryGroup: sudo
  additionalFiles:
    dracut-downloader-module/download-artifacts.sh: /usr/lib/dracut/modules.d/90micdownloader/download-artifacts.sh
    dracut-downloader-module/module-setup.sh: /usr/lib/dracut/modules.d/90micdownloader/module-setup.sh
    dracut-downloader-module/dracut-include-mic-downloader.conf: /etc/dracut.conf.d/90-dracut-include-mic-downloader.conf
    initrd-additional-artifacts/dracut-additional-files.conf: /etc/dracut.conf.d/91-dracut-additional-files.conf
    initrd-additional-artifacts/rootfs.img: /gmileka-workaround/rootfs.img