# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

pr:
  branches:
    include:
      - 1.0-dev
      - main
      - 3.0-dev
      - karimeldegwy/**

  paths:
    include:
      - SPECS/**
      - SPECS-EXTENDED/**

variables:
  - group: "Agent pools (DEV)"

resources:
  repositories:
    - repository: CBL-Mariner-Pipelines
      type: git
      name: mariner/CBL-Mariner-Pipelines

jobs:
  - job: 'MultiPackageCheck'
    pool:
      name: "$(DEV_AMD64_Ubuntu_Managed)"
      type: linux
      isCustom: true
    timeoutInMinutes: 15
    displayName: 'Add reviewer if multi-package addition/removal detected'
    steps:
      - script: |
          echo "Checking for multi-package addition/removal"
          result=$(./.github/workflows/check-multi-package-addition-removal.sh)
          echo "##vso[task.setvariable variable=MULTI_PACKAGE_ADD_REMOVE_DETECTED;isOutput=true]$result"
        displayName: 'Check Multi-package Addition/Removal'
        env:
          GITHUB_BASE_REF: $(System.PullRequest.TargetBranch)
          GITHUB_WORKSPACE: $(Build.SourcesDirectory)
        name: checkMultiPackage

      - template: pipelines/multi-package/AddMultiPackTeamAsReviewer.yml@CBL-Mariner-Pipelines
        condition: and(succeeded(), eq(dependencies.MultiPackageCheck.outputs['checkMultiPackage.MULTI_PACKAGE_ADD_REMOVE_DETECTED'], 'true'))
        parameters:
          prID: $(System.PullRequest.PullRequestId)
