# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Source Signature Check

on:
  push:
    branches: [3.0*]
  pull_request:
    branches: [3.0*]

jobs:
  spec-check:
    name: Source Signature Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v4

      - name: Check for invalid signatures
        run: |
          # Find the packages that have been modified in the current PR. They will be of the form '/path/to/SPECS/<pkgname>/**/.*', and we want to extract
          changed_pkgs=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }} | { grep "SPECS/.*" || test $? = 1; } | sed -n 's#SPECS/\([^/]*\)/.*#\1#p' | sort -u)
          changed_pkgs_extended=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }} | { grep "SPECS-EXTENDED/.*" || test $? = 1; } | sed -n 's#SPECS-EXTENDED/\([^/]*\)/.*#\1#p' | sort -u)
          if [ -z "${changed_pkgs}${changed_pkgs_extended}" ]; then
            echo "No package changes detected."
            exit 0
          fi
          echo "Checking for invalid signatures..."
          # Call this script to sync the toolchain manifests with the LKG daily build.
          ./toolkit/scripts/setuplkgtoolchain.sh
          # Determine the LKG daily build ID.
          LKG_BUILD_ID=$(wget -qO - https://mariner3dailydevrepo.blob.core.windows.net/lkg/lkg-3.0-dev.json | jq -r ".dailybuildid" | tr '\.' '-')

          if [ -n "${changed_pkgs}" ]; then
            sudo make -C toolkit -j$(nproc) input-srpms REBUILD_TOOLS=y DAILY_BUILD_ID=${LKG_BUILD_ID} SRPM_PACK_LIST="${changed_pkgs}"
            core_err=$?
          fi

          if [ -n "${changed_pkgs_extended}" ]; then
            sudo make -C toolkit -j$(nproc) input-srpms REBUILD_TOOLS=y DAILY_BUILD_ID=${LKG_BUILD_ID} SRPM_PACK_LIST="${changed_pkgs_extended} SPECS_DIR=SPECS-EXTENDED"
            extended_err=$?
          fi

          if [ $core_err -ne 0 ] || [ $extended_err -ne 0 ]; then
            echo "Failed to check the signatures of the modified packages."
            if [ $core_err -ne 0 ]; then
              echo "Consider running: sudo make -C toolkit input-srpms REBUILD_TOOLS=y DAILY_BUILD_ID=${LKG_BUILD_ID} SRPM_PACK_LIST='${changed_pkgs}'"
            elif [ $extended_err -ne 0 ]; then
              echo "Consider running: sudo make -C toolkit input-srpms REBUILD_TOOLS=y DAILY_BUILD_ID=${LKG_BUILD_ID} SRPM_PACK_LIST='${changed_pkgs_extended} SPECS_DIR=SPECS-EXTENDED'"
            fi
            exit 1
          fi
